#!/usr/bin/env bash
#
#for i in {1..100}
#do
#	if (( (i % 3 == 0) && (i % 5 == 0) )); then
#		echo "FizzBuzz"
#	elif ((i%3 == 0));then
#		echo "Fizz"
#	elif ((i%5 == 0));then
#		echo "Buzz"
#	else
#		echo "$i"
#	fi
#done

num=1

while [ $num -le 100 ]
do
	if [ $((num % 3)) -eq 0 ]; then
		if [ $((num % 5)) -eq 0 ]; then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif [ $((num % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$num"
	fi
	((num++))
done
