#!/usr/bin/env bash
#
# Open the /etc/passwd file for reading
while IFS=: read -r username password uid gid full_name home_directory shell; do
    # Display the username, user ID, and home directory
    echo "$username"
    echo "$uid"
    echo "$home_directory"
done < /etc/passwd
