#!/usr/bin/env bash
#
file="school"
if [ -e $file ]; then
	echo "school file exists"
	if [ cat $file|wc == 0]; then
	       echo "school file is empty"
        else
		echo "school file is not empty"		
	fi
	if [ -f $file]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
