#!/usr/bin/env bash
#
./manage_my_process
handle_start() {
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}

handle_stop() {
	if [ -f /var/run/my_process.pid ]; then
        	pid=$(cat /var/run/my_process.pid)
        	kill "$pid" 2>/dev/null
        	rm /var/run/my_process.pid
        	echo "manage_my_process stopped"
    	else
        	echo "No such PID file found."	
}

handle_restart() {
	if [ -f /var/run/my_process.pid ]; then
        	pid=$(cat /var/run/my_process.pid)
       		kill "$pid" 2>/dev/null
        	rm /var/run/my_process.pid
	fi
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

handle_else() {
	echo "Usage: manage_my_process {start|stop|restart}"
}

if [ "$1" == "stop" ]; then
        handle_stop
elif [ "$1" == "start" ]; then
        handle_start
elif [ "$1" == "restart" ]; then
        handle_restart
else
        handle_else
fi
