#!/usr/bin/env bash
#
./manage_my_process
handle_start() {
	./manage_my_process &
	PROCESS_NAME="manage_my_process"
        PID=$(pgrep -f "$PROCESS_NAME")
   
	echo "$PID" > /var/run/my_process.pid
	echo "manage_my_process started"
}

handle_stop() {
	PROCESS_NAME="manage_my_process"
	PID=$(pgrep -f "$PROCESS_NAME")
	kill -SIGQUIT "$PID"

	rm /var/run/my_process.pid
	echo "manage_my_process stopped"	
}

handle_restart() {
	PROCESS_NAME="manage_my_process"
        PID=$(pgrep -f "$PROCESS_NAME")
        kill -SIGQUIT "$PID"   
     	rm /var/run/my_process.pid

	./manage_my_process &
	PROCESS_NAME="manage_my_process"
        PID=$(pgrep -f "$PROCESS_NAME")
	echo "$PID" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

handle_else() {
	echo "Usage: manage_my_process {start|stop|restart}"
}

if [ "$1" == "stop" ]; then
        handle_stop
elif [ "$1" == "start" ]; then
        handle_start
elif [ "$1" == "restart" ]; then
        handle_restart
else
        handle_else
fi


