#!/usr/bin/env bash
#
# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM signal and call the handle_sigterm function
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
